/* test.svelte.js generated by Svelte VERSION */
import * as $ from 'svelte/internal/client';

let count = $.state(0);

export function get() {
	return $.get(count);
}

export function set() {
	$.update(count);
}