// Generates the per-platform `@lyku/parabun-bin-<os>-<arch>` npm packages
// from the built release artifacts. Each generated package is
// SELF-DESCRIBING: it carries the binary, its `os`/`cpu` (so npm only
// installs the matching one), the binary's relative path (`parabunBin`),
// and its own sha256 (`parabunSha256`). The umbrella `@lyku/parabun-bin`
// resolver (owned by the airgap/para repo) bakes its manifest from these
// fields — see /raid/para-design/para-parabun-boundary.md (P2, decision 1).
//
// Scope is ALWAYS @lyku/* (the only scope the org owns; @para/* is
// unpublishable). NEVER an oven-sh / upstream-Bun target.
//
// Usage:
//   bun scripts/publish/parabun-bin-packages.ts \
//     --artifacts artifacts --version 0.0.0-pin-<sha> --out .parabun-bin-dist
//
// Emits <out>/<pkgdir>/ ready for `npm publish`. Prints, one per line,
// each generated package dir (consumed by the Jenkins publish loop).

import { createHash } from "node:crypto";
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

type Platform = {
  artifact: string; // filename under --artifacts
  key: string; // resolver platform key (process.platform-process.arch mapped)
  pkg: string; // npm package name
  os: string; // package.json "os"
  cpu: string; // package.json "cpu"
  binName: string; // relative path the binary is shipped at
};

// Mirrors the Jenkinsfile Build matrix artifact names exactly.
const PLATFORMS: Platform[] = [
  {
    artifact: "parabun-linux-x64",
    key: "linux-x64",
    pkg: "@lyku/parabun-bin-linux-x64",
    os: "linux",
    cpu: "x64",
    binName: "bin/parabun",
  },
  {
    artifact: "parabun-linux-aarch64",
    key: "linux-arm64",
    pkg: "@lyku/parabun-bin-linux-arm64",
    os: "linux",
    cpu: "arm64",
    binName: "bin/parabun",
  },
  {
    artifact: "parabun-macos-arm64",
    key: "darwin-arm64",
    pkg: "@lyku/parabun-bin-darwin-arm64",
    os: "darwin",
    cpu: "arm64",
    binName: "bin/parabun",
  },
  {
    artifact: "parabun-windows-x64.exe",
    key: "win32-x64",
    pkg: "@lyku/parabun-bin-win32-x64",
    os: "win32",
    cpu: "x64",
    binName: "bin/parabun.exe",
  },
];

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const artifactsDir = arg("artifacts") ?? "artifacts";
const version = arg("version");
const outDir = arg("out") ?? ".parabun-bin-dist";

if (!version) {
  console.error("parabun-bin-packages: --version is required");
  process.exit(2);
}
if (!/^[0-9A-Za-z.+-]+$/.test(version)) {
  console.error(`parabun-bin-packages: invalid npm version "${version}"`);
  process.exit(2);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const generated: string[] = [];
for (const p of PLATFORMS) {
  const src = join(artifactsDir, p.artifact);
  if (!existsSync(src)) {
    // A platform may legitimately be absent (its BUILD_* param was off
    // for this run). Skip — never fabricate a package without a binary.
    console.error(`skip ${p.pkg}: no artifact ${src}`);
    continue;
  }
  const sha256 = createHash("sha256").update(readFileSync(src)).digest("hex");
  const pkgDir = join(outDir, p.key);
  mkdirSync(join(pkgDir, "bin"), { recursive: true });
  const dst = join(pkgDir, p.binName);
  copyFileSync(src, dst);
  chmodSync(dst, 0o755);
  writeFileSync(
    join(pkgDir, "package.json"),
    JSON.stringify(
      {
        name: p.pkg,
        version,
        description: `Pinned parabun release binary for ${p.key}. Binary carrier for @lyku/parabun-bin (P2 boundary). Generated by parabun Jenkins — do not hand-edit.`,
        os: [p.os],
        cpu: [p.cpu],
        parabunBin: p.binName,
        parabunSha256: sha256,
        files: ["bin/", "README.md"],
        license: "MIT",
        publishConfig: { access: "public" },
        repository: { type: "git", url: "https://github.com/airgap/parabun.git" },
      },
      null,
      2,
    ) + "\n",
  );
  writeFileSync(
    join(pkgDir, "README.md"),
    `# ${p.pkg}\n\nPlatform binary carrier for the pinned parabun release (\`${p.key}\`). ` +
      `Do not depend on this directly — depend on \`@lyku/parabun-bin\`, which resolves and ` +
      `sha256-verifies the matching platform package. Generated by parabun Jenkins.\n`,
  );
  console.error(`generated ${p.pkg}@${version} (${p.key}, sha256=${sha256.slice(0, 12)}…)`);
  generated.push(pkgDir);
}

if (generated.length === 0) {
  console.error("parabun-bin-packages: no artifacts found — nothing generated");
  process.exit(1);
}

// stdout = machine-readable list of dirs to `npm publish` (one per line).
for (const d of generated) console.log(d);
