/* state.svelte.js generated by Svelte VERSION */
import * as $ from 'svelte/internal/server';

export async function create_derived(get_promise, get_num) {
	let value = await $.async_derived(async () => (await $.save(get_promise()))() * get_num());

	return {
		get value() {
			return value();
		}
	};
}