/* store.svelte.js generated by Svelte VERSION */
import * as $ from 'svelte/internal/server';

class RawStore {
	values = { visible: true };

	get(key) {
		return this.values[key];
	}

	set(key, value) {
		this.values = { ...this.values, [key]: value };
	}
}

export const store = new RawStore();